export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_RANDOM = "GET_RANDOM";
export const GET_NEW_MOVIE_SUC = "GET_NEW_MOVIE_SUC";
export const GET_NEW_MOVIE_FETCH = "GET_NEW_MOVIE_FETCH";
export const GET_NEW_MOVIE_ERR = "GET_NEW_MOVIE_ERR";
